### PR TITLE
fix CI tests

### PR DESCRIPTION
**Pull request by StrikerRUS**
Simply bump versions of testing-related tools to the latest ones.

### CODE REVIEW

**Comment by izeigerman** [comment]
I don't mind bumping those versions but what does it fix exactly?

**Comment by StrikerRUS** [comment]
@izeigerman All recent PRs fail with
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/bin/coveralls", line 7, in <module>
    from coveralls.cli import main
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/__init__.py", line 2, in <module>
    from .api import Coveralls
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/api.py", line 13, in <module>
    from .reporter import CoverallReporter
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/reporter.py", line 10, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter'
```

fails

**Comment by izeigerman** [comment]
Yeah, I noticed that. I was wondering whether the root cause is known.

**Comment by StrikerRUS** [comment]
For the time of creating this PR there was only one mention of that error in some repo's jitter chat, which said it is incompatibility issue between pytest and coveralls.

**Pull request merged**
