### PR TITLE
fix future warning by avoiding importing private modules

### PR DESCRIPTION
**Pull request by StrikerRUS**
Prepare for next scikit-learn version.
```
E:\Miniconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
E:\Miniconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.linear_model.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
```

### CODE REVIEW

**Comment by izeigerman** [comment]
Hey @StrikerRUS, thanks for this PR! Why didn't we limit the area of impact to those modules mentioned in the warning? Eg I don't consider `sklearn.linear_model` or `sklearn.ensemble` to be private. Please note that initially we were trying to follow the Google style guide on imports - http://google.github.io/styleguide/pyguide.html#22-imports

**Comment by StrikerRUS** [comment]
Now Powershell job is failing. Refer to https://github.com/BayesWitnesses/m2cgen/pull/193#issuecomment-617776303 and https://github.com/BayesWitnesses/m2cgen/pull/199#issuecomment-621890344.

```
=================================== FAILURES ===================================
_ test_e2e[xgboost_XGBClassifier - powershell - train_model_classification_binary2] _
estimator = XGBClassifier(base_score=0.6, booster='gblinear', colsample_bylevel=None,
              colsample_bynode=None, colsamp...ambda=0, scale_pos_weight=1, subsample=None,
              tree_method=None, validate_parameters=False, verbosity=None)
executor_cls = <class 'tests.e2e.executors.powershell.PowershellExecutor'>

...

expected=[0.04921597 0.950784  ], actual=[0.0492156801663393, 0.950784319833661]
expected=[0.06305683 0.9369432 ], actual=[0.0630565194153174, 0.936943480584683]
expected=[0.1270023 0.8729977], actual=[0.127001843824201, 0.872998156175799]
expected=[0.0785104 0.9214896], actual=[0.0785098971788289, 0.921490102821171]
expected=[0.8055698  0.19443017], actual=[0.805566852256706, 0.194433147743294]
```

**Comment by StrikerRUS** [comment]
Interestingly that `expected` output sometimes doesn't equal to `1.0` while `actual` one does.

I'm afraid that the root cause is #188 because I don't remember this error happened before that PR.

**Comment by StrikerRUS** [comment]
Thanks for the review!
I removed all additional changes in imports. Now this PR only directly addresses FutureWarning.

**Pull request merged**
