### PR TITLE
Add support for Lua

### PR DESCRIPTION
**Pull request by ghost**
Lua is not as popular as Python or JavaScript. But Lua is the only language in which you can write fast and reliable API gateways, scripts for games, and many other cool things. It would be cool to add Lua support to m2cgen.

### CODE REVIEW

**Comment by izeigerman** [comment]
Hey @pinktoxin ! Thank you so much for contributing this! So sorry about the delay with the review. I've just got back from vacation and will do my best to find time to review this PR soon. Appreciate your patience!

**Comment by ghost** [comment]
Hello! Yesterday I tested the generated lua model in openresty and found a serious performance issue. My PR needs to be rewritten using one local lua table. I'll be back soon. Sorry for that

**Comment by ghost** [comment]
The problem was that you can't create more than 200 local variables, but using global variables is not a solution because these variables in openresty (for example) live until the request ends. In Lua, these variables live until the program exits. That is why it is highly recommended not to use them.

**Comment by ghost** [comment]
@izeigerman  Could you review the code?

**Pull request closed without merging**
