### PR TITLE
XGBoost DART is not supported

### PR DESCRIPTION
**Pull request by StrikerRUS**
To reproduce, set `booster='dart'` and `rate_drop` to any non-zero value.
https://xgboost.readthedocs.io/en/latest/parameter.html#additional-parameters-for-dart-booster-booster-dart

```
import numpy as np
import xgboost as xgb
import m2cgen as m2c

X = np.random.rand(10, 1)
y = np.random.rand(10)

est = xgb.XGBRegressor(n_estimators=10, rate_drop=0.3, 
                       booster="dart", random_state=42).fit(X, y)

code = m2c.export_to_python(est)
exec(code)

for X_row in X:
    y_pred = est.predict(X_row.reshape(1, -1), ntree_limit=10)
    y_pred_code = score(X_row)
    np.testing.assert_allclose(y_pred, y_pred_code)
```

```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatch: 100%
Max absolute difference: 0.12700433
Max relative difference: 0.5260299
 x: array([0.368444], dtype=float32)
 y: array(0.241439)
```

### CODE REVIEW

**Comment by izeigerman** [comment]
Wow, great catch, @StrikerRUS! Earlier I overlooked the fact that the default rate is set to 0.0 for XGBoost. Any idea why does it work for LightGBM? Can it be that LightGBM implementation drops trees during fitting, while XGBoost does this during prediction? Although the later seems pretty weird and improbable.

**Comment by StrikerRUS** [comment]
@izeigerman Thanks! To be honest, I have no idea... I guess that the [implementation](https://github.com/microsoft/LightGBM/pull/67) differs a lot. I'll try to test LightGBM with `xgboost_dart_mode=True`: https://github.com/microsoft/LightGBM/pull/139.

Possibly related: https://github.com/dmlc/xgboost/pull/5115.

**Comment by StrikerRUS** [comment]
> I'll try to test LightGBM with `xgboost_dart_mode=True`

```
import numpy as np
import lightgbm as lgb
import m2cgen as m2c

X = np.random.rand(100, 1)
y = np.random.rand(100)

est = lgb.LGBMRegressor(n_estimators=10, drop_rate=0.3, xgboost_dart_mode=True,
                        boosting_type="dart", random_state=42).fit(X, y)

code = m2c.export_to_python(est)
exec(code)

for X_row in X:
    y_pred = est.predict(X_row.reshape(1, -1))
    y_pred_code = score(X_row)
    np.testing.assert_allclose(y_pred, y_pred_code)
```

Raises no errors.

**Comment by izeigerman** [comment]
Thanks for checking!

**Comment by trivialfis** [comment]
Just out of curious, how does lgb's custom objective handle dart?

**Pull request merged**
