### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by Alisa-lisa**
The usage example is for python

### CODE REVIEW

**Comment by izeigerman** [comment]
Hi @Alisa-lisa ! Thank you so much for submitting this PR! The idea of that example was to demonstrate how using `m2cgen` API once can generate **Java** code from the trained linear regression model. This is why it says `Java` there. Perhaps this whole `Usage` section can be rewritten somehow to make it clearer and avoid this kind of confusion?

**Comment by Alisa-lisa** [comment]
Ah, the positioning was a bit misleading for me+)
Maybe breaking one-line phrase into 2 would be more understandable for noobs like me+)
like:
Here's a simple example of how a trained linear in model in one language can be represented in a different language.
Model training in Python:
{code}
Generated Java code:
{code}

**Comment by izeigerman** [comment]
@Alisa-lisa I really like your proposal! What if we specify that model training happens in Python specifically, since this the only way of model training `m2cgen` currently supports. Like:

Here's a simple example of how a linear model trained in Python environment can be represented in Java code:
{code}
Generated Java code:
{code}

**Comment by Alisa-lisa** [comment]
You mean: 
1. Show training in python
2. Equal code in Java
3. Generated code from python to Java?

Sounds perfect!

**Comment by izeigerman** [comment]
Hey @Alisa-lisa are you planning to finish this update or should I close this PR?

**Comment by izeigerman** [comment]
Closing this PR due to lack of activity.

**Pull request closed without merging**
